# Generated by Django 3.1.1 on 2020-09-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified_at', models.DateField(null=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=10)),
                ('favorite_hairstyle', models.CharField(max_length=50)),
                ('like_about_your_hair', models.CharField(max_length=255)),
                ('daily_hair_ritual', models.CharField(max_length=255)),
                ('products_used', models.CharField(max_length=255)),
                ('skin_problem', models.CharField(max_length=255)),
                ('profile_pic', models.CharField(max_length=50)),
                ('join_date', models.DateField(null=True)),
                ('email_verification_code', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
