# Generated by Django 3.1.1 on 2020-09-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('about_us', models.TextField(max_length=255)),
                ('facebook_link', models.CharField(max_length=255)),
                ('twitter_link', models.CharField(max_length=255)),
                ('youtube_link', models.CharField(max_length=255)),
                ('linkedin_link', models.CharField(max_length=255)),
                ('instagram_link', models.CharField(max_length=255)),
                ('latest_youtube_video_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='SheekyHub',
        ),
    ]
