# Generated by Django 3.1.1 on 2020-09-25 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
