# Generated by Django 3.1.1 on 2020-09-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='my_reviews',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sheekyhub_post',
            field=models.TextField(blank=True),
        ),
    ]
