# Generated by Django 3.1.1 on 2020-09-22 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='daily_hair_ritual',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='like_about_your_hair',
            field=models.TextField(blank=True),
        ),
    ]
