# Generated by Django 3.1.1 on 2020-09-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200924_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='snapchat_link',
            field=models.CharField(default=34, max_length=255),
            preserve_default=False,
        ),
    ]
