# Generated by Django 3.1.1 on 2020-09-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200925_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='suggested_time',
            new_name='appointment_time',
        ),
    ]
