# Generated by Django 3.1.1 on 2020-09-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_indexpage_snapchat_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='background_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='testimonial_author',
            field=models.CharField(default='anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='testimonial_author_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='testimonial_author_position',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='testimonials',
            field=models.TextField(blank=True),
        ),
    ]
