# Generated by Django 3.1.1 on 2020-09-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(verbose_name='Date created')),
                ('updated_at', models.DateTimeField(verbose_name='Date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('created_at', models.DateTimeField(verbose_name='Date created')),
                ('updated_at', models.DateTimeField(verbose_name='Date updated')),
            ],
        ),
    ]
