# Generated by Django 3.1.1 on 2020-09-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('sub_category_id', models.IntegerField()),
                ('created_at', models.DateTimeField(verbose_name='Date created')),
                ('updated_at', models.DateTimeField(verbose_name='Date updated')),
            ],
        ),
    ]
