# Generated by Django 3.1.1 on 2020-09-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
