# Generated by Django 3.1.1 on 2020-09-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_subcategory_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category_id',
        ),
    ]
